
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kausik N
 */
public class Table_Insert extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public Table_Insert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l_t = new javax.swing.JLabel();
        Go = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        table_dropdown = new javax.swing.JComboBox<>();
        nav = new javax.swing.JPanel();
        view_button = new javax.swing.JButton();
        account_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        add_delete_button = new javax.swing.JButton();
        back = new javax.swing.JButton();
        backhome = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        enter_values = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        column_list = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 72, 124));
        jPanel1.setLayout(null);

        l_t.setFont(new java.awt.Font("Century Gothic", 1, 88)); // NOI18N
        l_t.setForeground(new java.awt.Color(255, 255, 255));
        l_t.setText("Insert");
        jPanel1.add(l_t);
        l_t.setBounds(580, 0, 310, 109);

        Go.setBackground(new java.awt.Color(0, 255, 255));
        Go.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        Go.setForeground(new java.awt.Color(0, 0, 255));
        Go.setText("Insert");
        Go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoActionPerformed(evt);
            }
        });
        jPanel1.add(Go);
        Go.setBounds(670, 750, 180, 40);

        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(t1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(280, 490, 890, 240);

        table_dropdown.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        table_dropdown.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                table_dropdownItemStateChanged(evt);
            }
        });
        jPanel1.add(table_dropdown);
        table_dropdown.setBounds(380, 130, 270, 31);

        view_button.setBackground(new java.awt.Color(5, 32, 74));
        view_button.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        view_button.setForeground(new java.awt.Color(237, 234, 234));
        view_button.setText("VIEW");
        view_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_buttonActionPerformed(evt);
            }
        });

        account_button.setBackground(new java.awt.Color(5, 32, 74));
        account_button.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        account_button.setForeground(new java.awt.Color(237, 234, 234));
        account_button.setText("ACCOUNT");
        account_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                account_buttonActionPerformed(evt);
            }
        });

        update_button.setBackground(new java.awt.Color(5, 32, 74));
        update_button.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        update_button.setForeground(new java.awt.Color(237, 234, 234));
        update_button.setText("UPDATE");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        add_delete_button.setBackground(new java.awt.Color(5, 32, 74));
        add_delete_button.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        add_delete_button.setForeground(new java.awt.Color(237, 234, 234));
        add_delete_button.setText("INSERT/DELETE");
        add_delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_delete_buttonActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(5, 32, 74));
        back.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        back.setForeground(new java.awt.Color(237, 234, 234));
        back.setText("SIGN OUT");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        backhome.setBackground(new java.awt.Color(5, 32, 74));
        backhome.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        backhome.setForeground(new java.awt.Color(237, 234, 234));
        backhome.setText("BACK");
        backhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backhomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(nav);
        nav.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(view_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(add_delete_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(update_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(account_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(backhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addComponent(account_button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(view_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(add_delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(backhome, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel1.add(nav);
        nav.setBounds(0, 0, 220, 800);

        enter_values.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Edit"
            }
        ));
        jScrollPane3.setViewportView(enter_values);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(740, 170, 350, 310);

        jScrollPane4.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane4MouseWheelMoved(evt);
            }
        });

        column_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Details"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(column_list);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(380, 170, 340, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String Table;
String[] columns_in_table = new String[200];
int columns_in_table_size = 0;
String[] update_values = new String[200];

String Username;
String Password;
String Id;
String Category;
String Column;

String[] Selected_Ids;

int Constrain;

String[] insertable_tables = new String[10];
int insertable_tables_size = 0;
int viewable_tables_size = 0;
int updatable_tables_size = 0;

void MySQLConnector_GetUser(){
    try {
    Class.forName("java.sql.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/Hospital","root","mysql");
    String s1="select Username, Password, Id, Category from LoginDetails where LoggedIn = 1;";
    Statement st1 = con.createStatement();
    ResultSet rs = st1.executeQuery(s1);
    int rs_size = 0;
    while(rs.next()){
        Username = rs.getString("Username");
        Password = rs.getString("Password");
        Id = rs.getString("Id");
        Category = rs.getString("Category");
        
        rs_size++;
    }
    
    if(rs_size != 1){
        System.out.println("ERROR: Multiple or No LoggedIn users.");
    }
    
    rs.close();
    con.close();
    }
    catch(ClassNotFoundException | SQLException e){
        System.out.println(e.getMessage());
    }
}

void FindAccesibleTables(String category){
    if(category.equals("Admin")){
        viewable_tables_size = 8;

        updatable_tables_size = 8;
        
        insertable_tables[0] = "Doctors";
        insertable_tables[1] = "Patients";
        insertable_tables[2] = "Rooms";
        insertable_tables[3] = "Staff";
        insertable_tables[4] = "Lab";
        insertable_tables[5] = "Equipment";
        insertable_tables[6] = "MedicalStock";
        insertable_tables[7] = "PatientReport";
        insertable_tables_size = 8;
    }
    else if(category.equals("Doctor")){
        viewable_tables_size = 8;

        updatable_tables_size = 1;
        
        insertable_tables_size = 0;
    }
    else if(category.equals("Staff")){
        viewable_tables_size = 8;

        updatable_tables_size = 3;

        insertable_tables[0] = "Equipment";
        insertable_tables[1] = "MedicalStock";
        insertable_tables[2] = "Patients";
        insertable_tables_size = 3;
    }
    else if(category.equals("Patient")){
        viewable_tables_size = 2;

        updatable_tables_size = 0;

        insertable_tables_size = 0;
    }
}

void MySQLConnector_GetColumns(){
    try {
    Class.forName("java.sql.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/Hospital","root","mysql");
    String s1="show columns from "+Table+";";
    Statement st1 = con.createStatement();
    ResultSet rs = st1.executeQuery(s1);
    int rs_size = 0;
    while(rs.next()){
        columns_in_table[rs_size] = rs.getString("Field");
        
        rs_size++;
    }
    columns_in_table_size = rs_size;
    rs.close();
    con.close();
    }
    catch(ClassNotFoundException | SQLException e){
        System.out.println(e.getMessage());
    }
}

void InitTable(){
    
    DefaultTableModel dtmcolumn = (DefaultTableModel)column_list.getModel();
    dtmcolumn.setRowCount(0);
    DefaultTableModel dtmenter = (DefaultTableModel)enter_values.getModel();
    dtmenter.setRowCount(0);
    Object[] obj = new Object[1];
    for(int i=0;i<columns_in_table_size;i++){
        obj[0] = columns_in_table[i];
        dtmcolumn.addRow(obj);
    }
    
    
    DefaultTableModel dtm = (DefaultTableModel)t1.getModel();
    dtm.setColumnCount(0);
    dtm.setRowCount(0);
    for(int i=0;i<columns_in_table_size;i++){
        dtm.addColumn(columns_in_table[i]);
    }
    
    UpdateList();
}

void UpdateList(){
    Object[] row = new Object[1];
    row[0] = "";
    DefaultTableModel dtmenter = (DefaultTableModel)enter_values.getModel();
    for(int i=0;i<columns_in_table_size;i++){
        dtmenter.addRow(row);
    }
}

void UpdateTable(int condition, String value){
    try {
    Class.forName("java.sql.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/Hospital","root","mysql");
    String s1 = "select * from "+Table+";";
    if(condition == 1){
        s1 = "select * from "+Table+" where "+Column+" = '"+value+"';";
    }
    Statement st1 = con.createStatement();
    ResultSet rs = st1.executeQuery(s1);
    int rs_size = 0;
    while(rs.next()){
        Object[] row = new Object[columns_in_table_size];
        for(int i=0;i<columns_in_table_size;i++){
            row[i] = rs.getObject(columns_in_table[i]);
            if(row[i] == null){
                System.out.println("null present.");
                row[i] = "";
            }
        }
        DefaultTableModel dtm = (DefaultTableModel)t1.getModel();
        dtm.addRow(row);
        
        rs_size++;
    }
    rs.close();
    con.close();
    RowSizeFitter();
    }
    catch(ClassNotFoundException | SQLException e){
        System.out.println(e.getMessage());
    }
}


void GetInsertValues(){
    for(int i=0;i<enter_values.getRowCount();i++){
        update_values[i] = enter_values.getValueAt(i, 0).toString();
    }
}

void MySQLConnector_Insert(){
    GetInsertValues();
    try {
    Class.forName("java.sql.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/Hospital","root","mysql");
    String s="";
    Statement st1 = con.createStatement();
    s = "insert into "+Table+" values(";
    for(int i=0;i<columns_in_table_size;i++){
        s = s + "'"+update_values[i]+"'";
        if(i<columns_in_table_size-1)s = s + ", ";
    }
    s = s + ");";
    System.out.println(s);
    st1.executeUpdate(s);
    
    int[] common_columns = {0, 1};
    String condition_query = InsertConditions(common_columns);System.out.println(condition_query);
    Statement st2 = con.createStatement();
    st2.executeUpdate(condition_query);
    
    
    con.close();
    }
    catch(ClassNotFoundException | SQLException e){
        System.out.println(e.getMessage());
    }
}

String InsertConditions(int[] i){
    String s = "";
    if(Table.equals("Patients")){
        s = "insert into PatientReport(";
        for(int j=0;j<i.length;j++){
            s = s+columns_in_table[i[j]];
            if(j<i.length-1)s = s+", ";
        }
        s = s+") values(";
        for(int j=0;j<i.length;j++){
            s = s+"'"+update_values[i[j]]+"'";
            if(j<i.length-1)s = s+", ";
        }
        s = s+");";
    }
    
    return s;
}
        
        
void RowSizeFitter(){
    int row_height;
    if(column_list.getRowCount()>0){
            row_height = (280/column_list.getRowCount());
            if(row_height < 50)row_height = 50;
            column_list.setRowHeight(row_height);

            enter_values.setRowHeight(row_height);
    }
    if(t1.getRowCount()>0){
        row_height = (200/t1.getRowCount());
        t1.setRowHeight(row_height);
    }
    
}

    private void GoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoActionPerformed
int[] Selected_Ids_index;
Selected_Ids_index = t1.getSelectedRows();
Selected_Ids = new String[t1.getSelectedRowCount()];
DefaultTableModel dtm = (DefaultTableModel) t1.getModel();
for(int i=0;i<t1.getSelectedRowCount();i++){
    Selected_Ids[i] = t1.getValueAt(Selected_Ids_index[i], 0).toString();
}

MySQLConnector_Insert();

InitTable();
UpdateTable(0, "");

JOptionPane.showMessageDialog(this, "Successfully inserted.");
    }//GEN-LAST:event_GoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
update_button.setFocusable(false);
        
MySQLConnector_GetUser();
FindAccesibleTables(Category);
if(viewable_tables_size == 0){
    view_button.setVisible(false);
}
if(updatable_tables_size == 0){
    update_button.setVisible(false);
}
if(insertable_tables_size == 0){
    add_delete_button.setVisible(false);
}

for(int i=0;i<insertable_tables_size;i++){
    //if(!(insertable_tables[i].equals("Patients") || insertable_tables[i].equals("PatientReport")))
        table_dropdown.addItem(insertable_tables[i]);
}

int table_index = table_dropdown.getSelectedIndex();
Table = table_dropdown.getItemAt(table_index);

MySQLConnector_GetColumns();

InitTable();
UpdateTable(0, "");


JScrollPane spLeft = jScrollPane4;
JScrollPane spRight = jScrollPane3;
spLeft.getVerticalScrollBar().setModel(spRight.getVerticalScrollBar().getModel());
spLeft.setWheelScrollingEnabled(false);
spLeft.addMouseWheelListener(new MouseWheelListener() {
    public void mouseWheelMoved(MouseWheelEvent e) {
        spRight.dispatchEvent(e);
    }
});
    }//GEN-LAST:event_formWindowOpened

    private void table_dropdownItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_table_dropdownItemStateChanged
int table_index = table_dropdown.getSelectedIndex();
Table = table_dropdown.getItemAt(table_index);

MySQLConnector_GetColumns();


InitTable();
UpdateTable(0,"");
    }//GEN-LAST:event_table_dropdownItemStateChanged

    private void view_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_buttonActionPerformed
Table_View h = new Table_View();
Table_Insert.this.setVisible(false);
h.setVisible(true);
    }//GEN-LAST:event_view_buttonActionPerformed

    private void account_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_account_buttonActionPerformed
AccountDetailsPage h = new AccountDetailsPage();
Table_Insert.this.setVisible(false);
h.setVisible(true);
    }//GEN-LAST:event_account_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
Table_UpdatePageHome h = new Table_UpdatePageHome();
Table_Insert.this.setVisible(false);
h.setVisible(true);
    }//GEN-LAST:event_update_buttonActionPerformed

    private void add_delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_delete_buttonActionPerformed
Table_InsertDeleteHome h = new Table_InsertDeleteHome();
Table_Insert.this.setVisible(false);
h.setVisible(true);
    }//GEN-LAST:event_add_delete_buttonActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
LoginPage h = new LoginPage();
Table_Insert.this.setVisible(false);
h.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void jScrollPane4MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane4MouseWheelMoved

    }//GEN-LAST:event_jScrollPane4MouseWheelMoved

    private void backhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backhomeActionPerformed
        HomePage h = new HomePage();
        Table_Insert.this.setVisible(false);
        h.setVisible(true);
    }//GEN-LAST:event_backhomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Go;
    private javax.swing.JButton account_button;
    private javax.swing.JButton add_delete_button;
    private javax.swing.JButton back;
    private javax.swing.JButton backhome;
    private javax.swing.JTable column_list;
    private javax.swing.JTable enter_values;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel l_t;
    private javax.swing.JPanel nav;
    private javax.swing.JTable t1;
    private javax.swing.JComboBox<String> table_dropdown;
    private javax.swing.JButton update_button;
    private javax.swing.JButton view_button;
    // End of variables declaration//GEN-END:variables
}
