
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kausik N
 */
public class Table_View_Backup extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public Table_View_Backup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l_t = new javax.swing.JLabel();
        Go = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        column_dropdown = new javax.swing.JComboBox<>();
        value_text = new javax.swing.JTextField();
        table_dropdown = new javax.swing.JComboBox<>();
        checkbox = new javax.swing.JCheckBox();
        nav = new javax.swing.JPanel();
        view_button = new javax.swing.JButton();
        account_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        add_delete_button = new javax.swing.JButton();
        back = new javax.swing.JButton();
        backhome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        l_t.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        l_t.setForeground(new java.awt.Color(255, 204, 51));
        l_t.setText("View");
        jPanel1.add(l_t);
        l_t.setBounds(360, 20, 150, 48);

        Go.setBackground(new java.awt.Color(0, 255, 255));
        Go.setForeground(new java.awt.Color(0, 0, 255));
        Go.setText("Go");
        Go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoActionPerformed(evt);
            }
        });
        jPanel1.add(Go);
        Go.setBounds(390, 630, 111, 25);

        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(t1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 270, 630, 310);

        column_dropdown.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                column_dropdownItemStateChanged(evt);
            }
        });
        jPanel1.add(column_dropdown);
        column_dropdown.setBounds(250, 220, 210, 30);

        value_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                value_textActionPerformed(evt);
            }
        });
        value_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                value_textKeyReleased(evt);
            }
        });
        jPanel1.add(value_text);
        value_text.setBounds(490, 220, 210, 30);

        table_dropdown.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                table_dropdownItemStateChanged(evt);
            }
        });
        jPanel1.add(table_dropdown);
        table_dropdown.setBounds(300, 140, 270, 31);

        checkbox.setForeground(new java.awt.Color(255, 0, 0));
        checkbox.setText("Constraints?");
        checkbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxItemStateChanged(evt);
            }
        });
        jPanel1.add(checkbox);
        checkbox.setBounds(130, 220, 100, 30);

        view_button.setBackground(new java.awt.Color(0, 0, 0));
        view_button.setForeground(new java.awt.Color(0, 0, 255));
        view_button.setText("VIEW");
        view_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_buttonActionPerformed(evt);
            }
        });

        account_button.setBackground(new java.awt.Color(0, 255, 255));
        account_button.setForeground(new java.awt.Color(0, 51, 204));
        account_button.setText("Account");
        account_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                account_buttonActionPerformed(evt);
            }
        });

        update_button.setBackground(new java.awt.Color(0, 255, 255));
        update_button.setForeground(new java.awt.Color(0, 0, 255));
        update_button.setText("UPDATE");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        add_delete_button.setBackground(new java.awt.Color(0, 255, 255));
        add_delete_button.setForeground(new java.awt.Color(0, 0, 255));
        add_delete_button.setText("Insert / Delete");
        add_delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_delete_buttonActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 255, 255));
        back.setForeground(new java.awt.Color(0, 0, 255));
        back.setText("Sign Out");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        backhome.setBackground(new java.awt.Color(0, 255, 255));
        backhome.setForeground(new java.awt.Color(0, 0, 255));
        backhome.setText("Back");
        backhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backhomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(nav);
        nav.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(view_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(add_delete_button, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addComponent(update_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(account_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(backhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addComponent(account_button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(view_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add_delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addComponent(backhome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        jPanel1.add(nav);
        nav.setBounds(0, 0, 120, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String Table;
String[] columns_in_table = new String[20];
int columns_in_table_size = 0;
String Username;
String Password;
String Id;
String Category;
String Column;

int Constrain;

String[] viewable_tables = new String[10];
int viewable_tables_size = 0;
int updatable_tables_size = 0;
int deletable_tables_size = 0;

void MySQLConnector_GetUser(){
    try {
    Class.forName("java.sql.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/Hospital","root","mysql");
    String s1="select Username, Password, Id, Category from LoginDetails where LoggedIn = 1;";
    Statement st1 = con.createStatement();
    ResultSet rs = st1.executeQuery(s1);
    int rs_size = 0;
    while(rs.next()){
        Username = rs.getString("Username");
        Password = rs.getString("Password");
        Id = rs.getString("Id");
        Category = rs.getString("Category");
        
        rs_size++;
    }
    
    if(rs_size != 1){
        System.out.println("ERROR: Multiple or No LoggedIn users.");
    }
    
    rs.close();
    con.close();
    }
    catch(ClassNotFoundException | SQLException e){
        System.out.println(e.getMessage());
    }
}

void FindAccesibleTables(String category){
    if(category.equals("Admin")){
        viewable_tables[0] = "Doctors";
        viewable_tables[1] = "Patients";
        viewable_tables[2] = "Rooms";
        viewable_tables[3] = "Staff";
        viewable_tables[4] = "Lab";
        viewable_tables[5] = "Equipment";
        viewable_tables[6] = "MedicalStock";
        viewable_tables[7] = "PatientReport";
        viewable_tables_size = 8;
        
        updatable_tables_size = 8;

        deletable_tables_size = 8;
    }
    else if(category.equals("Doctor")){
        viewable_tables[0] = "Doctors";
        viewable_tables[1] = "Patients";
        viewable_tables[2] = "Rooms";
        viewable_tables[3] = "Staff";
        viewable_tables[4] = "Lab";
        viewable_tables[5] = "Equipment";
        viewable_tables[6] = "MedicalStock";
        viewable_tables[7] = "PatientReport";
        viewable_tables_size = 8;
        
        updatable_tables_size = 1;
        
        deletable_tables_size = 0;
    }
    else if(category.equals("Staff")){
        viewable_tables[0] = "Doctors";
        viewable_tables[1] = "Patients";
        viewable_tables[2] = "Rooms";
        viewable_tables[3] = "Staff";
        viewable_tables[4] = "Lab";
        viewable_tables[5] = "Equipment";
        viewable_tables[6] = "MedicalStock";
        viewable_tables[7] = "PatientReport";
        viewable_tables_size = 8;

        updatable_tables_size = 3;

        deletable_tables_size = 3;
    }
    else if(category.equals("Patient")){
        viewable_tables[0] = "Doctors";
        viewable_tables[1] = "PatientReport";
        viewable_tables_size = 2;

        updatable_tables_size = 0;

        deletable_tables_size = 0;
    }
}

void MySQLConnector_GetColumns(){
    try {
    Class.forName("java.sql.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/Hospital","root","mysql");
    String s1="show columns from "+Table+";";
    Statement st1 = con.createStatement();
    ResultSet rs = st1.executeQuery(s1);
    int rs_size = 0;
    while(rs.next()){
        columns_in_table[rs_size] = rs.getString("Field");
        
        rs_size++;
    }
    columns_in_table_size = rs_size;
    rs.close();
    con.close();
    }
    catch(ClassNotFoundException | SQLException e){
        System.out.println(e.getMessage());
    }
}

void InitTable(){
    DefaultTableModel dtm = (DefaultTableModel)t1.getModel();
    dtm.setColumnCount(0);
    dtm.setRowCount(0);
    for(int i=0;i<columns_in_table_size;i++){
        dtm.addColumn(columns_in_table[i]);
    }
}

void UpdateTable(int condition, String value){
    try {
    Class.forName("java.sql.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/Hospital","root","mysql");
    String s1 = "select * from "+Table+"";
    if(condition == 1){
        s1 = "select * from "+Table+" where "+Column+" = "+value+"";
        if(!(ConditionalViewing().equals(""))) s1 = s1+" and "+ConditionalViewing();
    }
    else {
        if(!(ConditionalViewing().equals(""))) s1 = s1 + " where " + ConditionalViewing();
    }
    
    Statement st1 = con.createStatement();
    s1 = s1+";";System.out.println(s1);
    ResultSet rs = st1.executeQuery(s1);
    int rs_size = 0;
    while(rs.next()){
        Object[] row = new Object[columns_in_table_size];
        for(int i=0;i<columns_in_table_size;i++){
            row[i] = rs.getObject(columns_in_table[i]);
            if(row[i] == null){
                System.out.println("null present.");
                row[i] = "";
            }
        }
        DefaultTableModel dtm = (DefaultTableModel)t1.getModel();
        dtm.addRow(row);
        
        rs_size++;
    }
    rs.close();
    con.close();
    RowSizeFitter();
    }
    catch(ClassNotFoundException | SQLException e){
        System.out.println(e.getMessage());
    }
}

String ConditionalViewing(){
    String s = "";
    if(Category.equals("Patient")){
        s = " PatientId = '"+Id+"'";
    }
    
    return s;
}

void RowSizeFitter(){
    System.out.println(t1.getSize().height);
    if(t1.getRowCount()>0){
        int row_height = (280/t1.getRowCount());
        t1.setRowHeight(row_height);
    }
}

    private void GoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoActionPerformed
DefaultTableModel dtm = (DefaultTableModel)t1.getModel();
dtm.setColumnCount(0);
dtm.setRowCount(0);
InitTable();
if(checkbox.isSelected() == true){
    Constrain = 1;
    String val = value_text.getText();
    int error = 0;
    int val_temp = 0;
    try{
        val_temp = Integer.parseInt(val);
        
    }
    catch(Exception e){
        error = 1;
    }
    if(error == 0)val = val_temp+"";
    else val = "'"+val+"'";
    if(val.equals("''") || val.equals(""))Constrain=0;
    UpdateTable(Constrain, val);
}
else if(checkbox.isSelected() == false){
    Constrain = 0;
    UpdateTable(Constrain, "");
}
    }//GEN-LAST:event_GoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
Go.setVisible(false);
        
view_button.setFocusable(false);
        
MySQLConnector_GetUser();
FindAccesibleTables(Category);
if(viewable_tables_size == 0){
    view_button.setVisible(false);
}
if(updatable_tables_size == 0){
    update_button.setVisible(false);
}
if(deletable_tables_size == 0){
    add_delete_button.setVisible(false);
}

for(int i=0;i<viewable_tables_size;i++){
    table_dropdown.addItem(viewable_tables[i]);
}

int table_index = table_dropdown.getSelectedIndex();
Table = table_dropdown.getItemAt(table_index);
        
column_dropdown.removeAllItems();
MySQLConnector_GetColumns();
for(int i=0;i<columns_in_table_size;i++){
    column_dropdown.addItem(columns_in_table[i]);
}

int column_index = 0;
Column = column_dropdown.getItemAt(column_index);

column_dropdown.setEnabled(false);
value_text.setEnabled(false);


InitTable();
UpdateTable(0, "");
    }//GEN-LAST:event_formWindowOpened

    private void table_dropdownItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_table_dropdownItemStateChanged
int table_index = table_dropdown.getSelectedIndex();
Table = table_dropdown.getItemAt(table_index);

column_dropdown.removeAllItems();
MySQLConnector_GetColumns();
for(int i=0;i<columns_in_table_size;i++){
    column_dropdown.addItem(columns_in_table[i]);
}

InitTable();
UpdateTable(0,"");
    }//GEN-LAST:event_table_dropdownItemStateChanged

    private void column_dropdownItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_column_dropdownItemStateChanged
int column_index = 0;
Column = column_dropdown.getItemAt(column_index);
    }//GEN-LAST:event_column_dropdownItemStateChanged

    private void checkboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxItemStateChanged
if(checkbox.isSelected() == true){
    column_dropdown.setEnabled(true);
    value_text.setEnabled(true);
    Constrain = 1;
    //String val = value_text.getText();
    //UpdateTable(Constrain, val);
}
else if(checkbox.isSelected() == false){
    column_dropdown.setEnabled(false);
    value_text.setEnabled(false);
    Constrain = 0;
    //UpdateTable(Constrain, "");
}


DefaultTableModel dtm = (DefaultTableModel)t1.getModel();
dtm.setColumnCount(0);
dtm.setRowCount(0);
InitTable();
if(checkbox.isSelected() == true){
    Constrain = 1;
    Column = column_dropdown.getItemAt(column_dropdown.getSelectedIndex());
    String val = value_text.getText();
    int error = 0;
    int val_temp = 0;
    try{
        val_temp = Integer.parseInt(val);
        
    }
    catch(Exception e){
        error = 1;
    }
    if(error == 0)val = val_temp+"";
    else val = "'"+val+"'";
    if(val.equals("''") || val.equals(""))Constrain=0;
    UpdateTable(Constrain, val);
}
else if(checkbox.isSelected() == false){
    Constrain = 0;
    UpdateTable(Constrain, "");
}
    }//GEN-LAST:event_checkboxItemStateChanged

    private void view_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_buttonActionPerformed

    }//GEN-LAST:event_view_buttonActionPerformed

    private void account_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_account_buttonActionPerformed
AccountDetailsPage h = new AccountDetailsPage();
Table_View_Backup.this.setVisible(false);
h.setVisible(true);
    }//GEN-LAST:event_account_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
Table_UpdatePageHome h = new Table_UpdatePageHome();
Table_View_Backup.this.setVisible(false);
h.setVisible(true);
    }//GEN-LAST:event_update_buttonActionPerformed

    private void add_delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_delete_buttonActionPerformed
Table_InsertDeleteHome h = new Table_InsertDeleteHome();
Table_View_Backup.this.setVisible(false);
h.setVisible(true);
    }//GEN-LAST:event_add_delete_buttonActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
LoginPage h = new LoginPage();
Table_View_Backup.this.setVisible(false);
h.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void value_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_value_textActionPerformed
    }//GEN-LAST:event_value_textActionPerformed

    private void value_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_value_textKeyReleased
DefaultTableModel dtm = (DefaultTableModel)t1.getModel();
dtm.setColumnCount(0);
dtm.setRowCount(0);
InitTable();
if(checkbox.isSelected() == true){
    Constrain = 1;
    Column = column_dropdown.getItemAt(column_dropdown.getSelectedIndex());
    String val = value_text.getText();
    int error = 0;
    int val_temp = 0;
    try{
        val_temp = Integer.parseInt(val);
        
    }
    catch(Exception e){
        error = 1;
    }
    if(error == 0)val = val_temp+"";
    else val = "'"+val+"'";
    UpdateTable(Constrain, val);
}
else if(checkbox.isSelected() == false){
    Constrain = 0;
    UpdateTable(Constrain, "");
}
    }//GEN-LAST:event_value_textKeyReleased

    private void backhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backhomeActionPerformed
        HomePage h = new HomePage();
        Table_View_Backup.this.setVisible(false);
        h.setVisible(true);
    }//GEN-LAST:event_backhomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Go;
    private javax.swing.JButton account_button;
    private javax.swing.JButton add_delete_button;
    private javax.swing.JButton back;
    private javax.swing.JButton backhome;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JComboBox<String> column_dropdown;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_t;
    private javax.swing.JPanel nav;
    private javax.swing.JTable t1;
    private javax.swing.JComboBox<String> table_dropdown;
    private javax.swing.JButton update_button;
    private javax.swing.JTextField value_text;
    private javax.swing.JButton view_button;
    // End of variables declaration//GEN-END:variables
}
